import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../Components/Header';
import Card1 from '../Components/Card1';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Coffee Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Card1 />
        {children}</body>
    </html>
  )
}
